from __future__ import annotations

VOICES = [
    {"index": 0, "number": 9, "folder": "09_中音・穏やか・物語調", "speaker_id": "speaker_08458", "seed": 202608050900},
    {"index": 1, "number": 10, "folder": "10_中音・冷静・少し硬め", "speaker_id": "speaker_03183", "seed": 202608051000},
    {"index": 2, "number": 11, "folder": "11_中音・芯強め・クール", "speaker_id": "speaker_09784", "seed": 202608051100},
    {"index": 3, "number": 12, "folder": "12_中高音・囁き・近距離", "speaker_id": "speaker_04428", "seed": 202608051200},
    {"index": 4, "number": 13, "folder": "13_中高音・やさしい・透明", "speaker_id": "speaker_02022", "seed": 202608051300},
    {"index": 5, "number": 14, "folder": "14_中高音・丁寧・明瞭", "speaker_id": "speaker_01635", "seed": 202608051400},
    {"index": 6, "number": 15, "folder": "15_中高音・やわらかい・丸い", "speaker_id": "speaker_01639", "seed": 202608051500},
    {"index": 7, "number": 16, "folder": "16_中高音・軽快・話しやすい", "speaker_id": "speaker_01281", "seed": 202608051600},
    {"index": 8, "number": 17, "folder": "17_高い・小さめ・落ち着き", "speaker_id": "speaker_00526", "seed": 202608051700},
    {"index": 9, "number": 18, "folder": "18_高い・親密・息少なめ", "speaker_id": "speaker_09925", "seed": 202608051800},
    {"index": 10, "number": 19, "folder": "19_高い・軽い・自然会話", "speaker_id": "speaker_03333", "seed": 202608051900},
    {"index": 11, "number": 20, "folder": "20_高い・明るい・息多め", "speaker_id": "speaker_00703", "seed": 202608052000},
    {"index": 12, "number": 21, "folder": "21_かなり高い・元気・軽快", "speaker_id": "speaker_02196", "seed": 202608052100},
    {"index": 13, "number": 22, "folder": "22_かなり高い・繊細・透明", "speaker_id": "speaker_02829", "seed": 202608052200},
    {"index": 14, "number": 23, "folder": "23_かなり高い・はきはき・細め", "speaker_id": "speaker_00162", "seed": 202608052300},
    {"index": 15, "number": 24, "folder": "24_非常に高い・鋭い・感情的", "speaker_id": "speaker_09137", "seed": 202608052400},
]

# Filename, spoken line, and acting instruction are one-to-one.
# Short, mostly-hiragana lines reduce reading errors and hallucinated continuations.
STYLES = [
    {
        "number": 1,
        "label": "丁寧で落ち着いた話し方",
        "short": "こちらをゆっくり見てください",
        "text": "こちらを、ゆっくり、みてください。",
        "input_text": "こちらを、ゆっくり、みてください。",
        "caption": "丁寧で穏やかな案内。落ち着いた速度と小さめの声量で、すべての音を明瞭に発音する。語尾まで柔らかく、急に声を張らない。",
        "mode": "polite",
        "duration_scale": 1.05,
        "candidate_count": 3,
        "acting_minimum": 0.0,
    },
    {
        "number": 2,
        "label": "自然な日常会話",
        "short": "きょういっしょに帰らない",
        "text": "ねえ、きょう、いっしょに、かえらない？",
        "input_text": "ねえ、きょう、いっしょに、かえらない？",
        "caption": "親しい相手への自然な日常会話。普通より少し小さな近距離の声で、力まず自然に話す。演技を誇張せず、叫ばず、最後まで会話の調子を保つ。",
        "mode": "neutral",
        "duration_scale": 1.00,
        "candidate_count": 3,
        "acting_minimum": 0.0,
    },
    {
        "number": 3,
        "label": "明るくうれしい話し方",
        "short": "会えてほんとうにうれしい",
        "text": "やった。あえて、ほんとうに、うれしい。",
        "input_text": "やった。あえて、ほんとうに、うれしい。😊",
        "caption": "心からうれしく、笑顔が声に表れている。明るく弾む抑揚で少し速めに話す。言葉は明瞭に保ち、絶叫や余計な笑い声を足さない。",
        "mode": "happy",
        "duration_scale": 0.96,
        "candidate_count": 4,
        "acting_minimum": 0.52,
    },
    {
        "number": 4,
        "label": "少し怒った話し方",
        "short": "もう同じことはしないで",
        "text": "もう、やめて。おなじことは、しないで。",
        "input_text": "もう、やめて。おなじことは、しないで。😠",
        "caption": "怒りと不満が明確に伝わるが、感情を抑えている。声の芯を強くし、重要な言葉と語尾へ圧を置く。絶叫や金切り声にはしない。",
        "mode": "angry",
        "duration_scale": 0.97,
        "candidate_count": 4,
        "acting_minimum": 0.52,
    },
    {
        "number": 5,
        "label": "悲しく弱った話し方",
        "short": "きょうは少しつらいの",
        "text": "ごめん。きょうは、すこし、つらいの。",
        "input_text": "ごめん。きょうは、すこし、つらいの。😭",
        "caption": "悲しみで気力が落ち、今にも涙がこぼれそうな弱い声。少し震えても、言葉は明瞭に保つ。明るくせず、怒鳴らず、最後まで弱った調子で話す。",
        "mode": "sad",
        "duration_scale": 1.12,
        "candidate_count": 4,
        "acting_minimum": 0.52,
    },
    {
        "number": 6,
        "label": "怖がって慌てた話し方",
        "short": "そこにだれかいる",
        "text": "まって。そこに、だれか、いる。",
        "input_text": "まって。そこに、だれか、いる。😰",
        "caption": "本気で怖がり、動揺して息が浅い。少し速く、声が軽く震える。悲鳴で台詞を潰さず、すべての言葉を聞き取れるように話す。",
        "mode": "fear",
        "duration_scale": 0.96,
        "candidate_count": 4,
        "acting_minimum": 0.42,
    },
    {
        "number": 7,
        "label": "眠く力の抜けた話し方",
        "short": "ごめんまだ眠いの",
        "text": "ごめん。まだ、ねむいの。",
        "input_text": "ごめん。まだ、ねむいの。😪😮‍💨",
        "caption": "本当に眠く、まぶたが重く、全身の力が抜けている。非常に小さな声でゆっくり話し、語尾を下げる。元気にせず、叫ばず、余計なあくびや言葉を足さない。",
        "mode": "sleepy",
        "duration_scale": 1.18,
        "candidate_count": 4,
        "acting_minimum": 0.52,
    },
    {
        "number": 8,
        "label": "やさしく心配する話し方",
        "short": "ここで少し休もう",
        "text": "むりしなくて、いいよ。ここで、すこし、やすもう。",
        "input_text": "むりしなくて、いいよ。ここで、すこし、やすもう。🫶😟",
        "caption": "弱っている相手を心から気遣う、やさしく包み込む声。小さめの声量と少し遅い速度で、安心させるように話す。説教調や怒りにしない。",
        "mode": "gentle",
        "duration_scale": 1.09,
        "candidate_count": 3,
        "acting_minimum": 0.48,
    },
    {
        "number": 9,
        "label": "ゆったりした独り言",
        "short": "きょうは静かでいいな",
        "text": "きょうは、しずかで、いいな。",
        "input_text": "きょうは、しずかで、いいな。🐢📖",
        "caption": "ひとりで静かに考えながら話す、ゆったりした独り言。速度を落とし、自然な間を取り、感情を誇張しない。声を張らず、落ち着いた余韻を残す。",
        "mode": "monologue",
        "duration_scale": 1.14,
        "candidate_count": 3,
        "acting_minimum": 0.48,
    },
    {
        "number": 10,
        "label": "笑い混じりの話し方",
        "short": "ちゃんとわかってるよ",
        "text": "ふふっ。ちゃんと、わかってるよ。",
        "input_text": "ふふっ。ちゃんと、わかってるよ。🤭",
        "caption": "最初に短く自然にくすっと笑い、その後も微笑みが声ににじむ。笑いで台詞を潰さず、すべての言葉を明瞭に話し、最後へ余計な笑いを足さない。",
        "mode": "laugh",
        "duration_scale": 1.04,
        "candidate_count": 4,
        "acting_minimum": 0.48,
    },
]

COMMON_CAPTION = (
    "声質と話者の個性は参照音声と同じ人物として厳密に保つ。"
    "静かな防音環境で、広帯域の高品質マイクを使った乾いた近接収録。"
    "元の声の自然な厚みを保ち、こもり、かすれ、鼻声、舌足らずさ、金属的なざらつき、ヒス、部屋鳴りを加えない。"
    "指定された短い台詞だけを最初から最後まで明瞭に話し、終了後は完全に黙る。"
)
